import { Restaurant, Category, Voucher, TimeSlot, HeroSlide, MenuCategory } from './types';

export const categories: Category[] = [
  { id: 'vietnamese', name: 'Vietnamese', icon: '🍜' },
  { id: 'japanese', name: 'Japanese', icon: '🍱' },
  { id: 'italian', name: 'Italian', icon: '🍝' },
  { id: 'korean', name: 'Korean', icon: '🥘' },
  { id: 'thai', name: 'Thai', icon: '🌶️' },
  { id: 'fusion', name: 'Fusion', icon: '🍲' },
  { id: 'dessert', name: 'Dessert', icon: '🍰' },
  { id: 'coffee', name: 'Coffee', icon: '☕' },
];

export const heroSlides: HeroSlide[] = [
  {
    id: 'hero-1',
    image: '/images/hero-1.jpg',
    title: 'Romantic Dining',
    subtitle: 'Create unforgettable memories with your loved one',
  },
  {
    id: 'hero-2',
    image: '/images/hero-2.jpg',
    title: 'Sunset Moments',
    subtitle: 'Experience love under the stars at rooftop venues',
  },
  {
    id: 'hero-3',
    image: '/images/hero-3.jpg',
    title: 'Culinary Excellence',
    subtitle: 'Taste the finest cuisines in the most intimate settings',
  },
];

export const menuCategories: MenuCategory[] = [
  {
    id: 'appetizers',
    name: 'Appetizers',
    items: [
      {
        id: 'app-1',
        name: 'Spring Rolls',
        price: 45000,
        description: 'Fresh Vietnamese spring rolls with peanut sauce',
        image: '/images/menu-appetizer.jpg',
      },
      {
        id: 'app-2',
        name: 'Shrimp Toast',
        price: 65000,
        description: 'Crispy shrimp toast with sweet chili',
        image: '/images/menu-appetizer.jpg',
      },
    ],
  },
  {
    id: 'mains',
    name: 'Main Courses',
    items: [
      {
        id: 'main-1',
        name: 'Premium Pho',
        price: 85000,
        description: 'Slow-cooked beef pho with fresh herbs',
        image: '/images/menu-main.jpg',
      },
      {
        id: 'main-2',
        name: 'Grilled Sea Bass',
        price: 125000,
        description: 'Fresh grilled sea bass with lemongrass',
        image: '/images/menu-main.jpg',
      },
    ],
  },
  {
    id: 'desserts',
    name: 'Desserts',
    items: [
      {
        id: 'dessert-1',
        name: 'Mango Sticky Rice',
        price: 35000,
        description: 'Sweet sticky rice with fresh mango',
        image: '/images/menu-dessert.jpg',
      },
      {
        id: 'dessert-2',
        name: 'Chocolate Lava Cake',
        price: 45000,
        description: 'Warm chocolate cake with vanilla ice cream',
        image: '/images/menu-dessert.jpg',
      },
    ],
  },
];

export const restaurants: Restaurant[] = [
  {
    id: 'saigon-kitchen',
    name: 'Saigon Kitchen',
    cuisine: 'Vietnamese',
    image: '/images/restaurant-saigon-kitchen.jpg',
    rating: 4.8,
    reviewCount: 342,
    deliveryTime: '25-35 mins',
    minOrder: 50000,
    tags: ['Pho', 'Banh Mi', 'Vegetarian'],
    description: 'Authentic Vietnamese cuisine with traditional recipes passed down through generations.',
    phone: '028 1234 5678',
    address: '123 Nguyen Hue, District 1, HCMC',
    hours: '10:00 - 22:00',
    specials: ['Pho Special - 10% off', 'Free delivery on orders > 200k'],
  },
  {
    id: 'edo-japan',
    name: 'Edo Japan',
    cuisine: 'Japanese',
    image: '/images/restaurant-edo-japan.jpg',
    rating: 4.7,
    reviewCount: 256,
    deliveryTime: '30-40 mins',
    minOrder: 100000,
    tags: ['Sushi', 'Ramen', 'Premium'],
    description: 'Premium Japanese cuisine featuring fresh sushi and authentic ramen bowls.',
    phone: '028 9876 5432',
    address: '456 Hoang Dieu, District 4, HCMC',
    hours: '11:00 - 23:00',
    specials: ['Valentine Special - 20% off couples meals'],
  },
  {
    id: 'bella-italia',
    name: 'Bella Italia',
    cuisine: 'Italian',
    image: '/images/restaurant-bella-italia.jpg',
    rating: 4.6,
    reviewCount: 189,
    deliveryTime: '25-35 mins',
    minOrder: 80000,
    tags: ['Pasta', 'Pizza', 'Wine'],
    description: 'Authentic Italian flavors with imported ingredients and traditional cooking techniques.',
    phone: '028 5555 6666',
    address: '789 Tran Hung Dao, District 1, HCMC',
    hours: '11:30 - 23:30',
    specials: ['Wine pairing - 15% discount'],
  },
  {
    id: 'korean-bbq-house',
    name: 'Korean BBQ House',
    cuisine: 'Korean',
    image: '/images/restaurant-korean-bbq.jpg',
    rating: 4.9,
    reviewCount: 420,
    deliveryTime: '20-30 mins',
    minOrder: 150000,
    tags: ['BBQ', 'Korean', 'Groups'],
    description: 'Premium Korean BBQ experience with table cooking and premium cuts of meat.',
    phone: '028 3333 4444',
    address: '321 Vo Van Tan, District 3, HCMC',
    hours: '16:00 - 24:00',
    specials: ['Group discount - 5+ people get 10% off'],
  },
  {
    id: 'pad-thai-paradise',
    name: 'Pad Thai Paradise',
    cuisine: 'Thai',
    image: '/images/restaurant-pad-thai.jpg',
    rating: 4.5,
    reviewCount: 287,
    deliveryTime: '25-35 mins',
    minOrder: 60000,
    tags: ['Thai', 'Spicy', 'Vegetarian'],
    description: 'Authentic Thai cuisine with customizable spice levels and fresh herbs.',
    phone: '028 7777 8888',
    address: '555 Ben Thanh, District 1, HCMC',
    hours: '11:00 - 21:00',
    specials: ['Lunch combo - 30% off 11:00-14:00'],
  },
  {
    id: 'sunset-fusion',
    name: 'Sunset Fusion',
    cuisine: 'Fusion',
    image: '/images/restaurant-sunset-fusion.jpg',
    rating: 4.4,
    reviewCount: 198,
    deliveryTime: '30-40 mins',
    minOrder: 120000,
    tags: ['Fusion', 'Modern', 'Romantic'],
    description: 'Creative fusion dishes blending Asian and Western culinary traditions.',
    phone: '028 2222 3333',
    address: '888 Ly Tu Trong, District 1, HCMC',
    hours: '17:00 - 23:00',
    specials: ['Happy hour - 6PM-7PM, 25% off drinks'],
  },
];

export const vouchers: Voucher[] = [
  {
    id: 'valentine-2026',
    code: 'LOVE2026',
    title: 'Valentine Special',
    description: 'Get 20% off your romantic dinner. Valid until Feb 14, 2026.',
    discount: '20% OFF',
    validity: 'Until 14 Feb',
    icon: '💝',
  },
  {
    id: 'welcome-new',
    code: 'WELCOME50K',
    title: 'Welcome Bonus',
    description: 'First order discount. Get 50,000 VND off.',
    discount: '50K OFF',
    validity: 'Until 28 Feb',
    icon: '🎉',
  },
  {
    id: 'lunch-combo',
    code: 'LUNCH30',
    title: 'Lunch Combo Deal',
    description: 'Save big on lunch orders between 11AM - 2PM.',
    discount: '30% OFF',
    validity: 'Daily 11-14h',
    icon: '🍽️',
  },
  {
    id: 'free-delivery',
    code: 'FREEDELIV',
    title: 'Free Delivery',
    description: 'Orders above 200,000 VND get free delivery.',
    discount: 'FREE',
    validity: 'Always',
    icon: '🚗',
  },
];

export const timeSlots: TimeSlot[] = [
  { id: 'slot-11', time: '11:00 AM', available: true },
  { id: 'slot-12', time: '12:00 PM', available: true },
  { id: 'slot-13', time: '1:00 PM', available: false },
  { id: 'slot-14', time: '2:00 PM', available: true },
  { id: 'slot-17', time: '5:00 PM', available: true },
  { id: 'slot-18', time: '6:00 PM', available: false },
  { id: 'slot-19', time: '7:00 PM', available: true },
  { id: 'slot-20', time: '8:00 PM', available: true },
  { id: 'slot-21', time: '9:00 PM', available: true },
];
