import { Restaurant, Category, Voucher, TimeSlot, HeroSlide, MenuCategory } from './types';

export const categories: Category[] = [
  { id: 'street-food', name: 'Hẹn hò vỉa hè', icon: '🍜' },
  { id: 'luxury', name: 'Hẹn hò sang trọng', icon: '🍷' },

];

export const heroSlides: HeroSlide[] = [
  {
    id: 'hero-1',
    image: '/images/hero-1.jpg',
    title: 'Hẹn hò lãng mạn',
    subtitle: 'Tạo nên những kỷ niệm khó quên cùng người thương của bạn',
  },
  {
    id: 'hero-2',
    image: '/images/hero-2.jpg',
    title: 'Khoảnh khắc hoàng hôn',
    subtitle: 'Trải nghiệm tình yêu lãng mạn dưới những vì sao tại không gian sân thượng',
  },
  {
    id: 'hero-3',
    image: '/images/hero-3.jpg',
    title: 'Tinh hoa ẩm thực',
    subtitle: 'Thưởng thức những món ăn hảo hạng trong không gian thân mật nhất',
  },
];

export const menuCategories: MenuCategory[] = [
  {
    id: 'appetizers',
    name: 'Món khai vị',
    items: [
      {
        id: 'app-1',
        name: 'Nem cuốn tươi',
        price: 45000,
        description: 'Nem cuốn tươi kiểu Việt Nam thanh mát kèm sốt tương đậu phộng đậm đà',
        image: 'https://images.unsplash.com/photo-1541014741259-de529411b96a?w=400',
      },
      {
        id: 'app-2',
        name: 'Bánh mì chiên tôm',
        price: 65000,
        description: 'Bánh mì tôm chiên giòn rụm ăn kèm với tương ớt ngọt dịu',
        image: 'https://images.unsplash.com/photo-1541014741259-de529411b96a?w=400',
      },
    ],
  },
  {
    id: 'mains',
    name: 'Món ăn chính',
    items: [
      {
        id: 'main-1',
        name: 'Phở bò đặc biệt',
        price: 85000,
        description: 'Phở bò nước dùng hầm kỹ từ xương ống chuẩn vị truyền thống kèm rau thơm',
        image: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=400',
      },
      {
        id: 'main-2',
        name: 'Cá vược nướng sả chanh',
        price: 125000,
        description: 'Cá vược tươi sống nướng thơm lừng hòa quyện cùng hương vị sả và chanh',
        image: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=400',
      },
    ],
  },
  {
    id: 'desserts',
    name: 'Món tráng miệng',
    items: [
      {
        id: 'dessert-1',
        name: 'Xôi xoài dừa',
        price: 35000,
        description: 'Xôi nếp dẻo thơm cốt dừa ăn kèm với xoài chín ngọt lịm',
        image: 'https://images.unsplash.com/photo-1563805042-7684c019e1cb?w=400',
      },
      {
        id: 'dessert-2',
        name: 'Bánh Chocolate Lava',
        price: 45000,
        description: 'Bánh ngọt chocolate nhân tan chảy ấm nóng kèm một viên kem vani',
        image: 'https://images.unsplash.com/photo-1563805042-7684c019e1cb?w=400',
      },
    ],
  },
];

const defaultGallery = [
  '/images/bundau.jpg',
  '/images/bundau1.jpg',
  'https://images.unsplash.com/photo-1424847651672-bf20a4b0982b?w=600',
  'https://images.unsplash.com/photo-1559339352-11d035aa65de?w=600',
];

export const restaurants: Restaurant[] = [
  {
    id: 'bun-dau-hang-khay',
    name: 'Bún Đậu Hàng Khay',
    cuisine: 'Hẹn hò vỉa hè',
    image: '/images/Hẹn hò vỉa hè/Bún đậu/bundau.jpg',
    gallery: [
      '/images/Hẹn hò vỉa hè/Bún đậu/bundau.jpg',
      '/images/Hẹn hò vỉa hè/Bún đậu/bundau1.jpg',
    ],
    rating: 4.8,
    reviewCount: 342,
    deliveryTime: '15-25 phút',
    minOrder: 50000,
    tags: ['Bún đậu', 'Phố cổ', 'Dân dã'],
    description: 'Quán bún đậu mắm tôm nức tiếng khu vực phố cổ, không gian vỉa hè dân dã, nhộn nhịp, lý tưởng cho những cặp đôi thích sự giản dị và thoải mái.',
    phone: '024 1234 5678',
    address: 'Ngõ 31 Hàng Khay, Quận Hoàn Kiếm, Hà Nội',
    hours: '10:00 - 20:30',
    specials: ['Tặng kèm trà đá', 'Giảm 5% khi check-in'],
  },

  {
    id: 'salmonoid',
    name: 'Salmonoid',
    cuisine: 'Không gian riêng tư', 
    image: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=800',
    gallery: defaultGallery,
    rating: 4.6,
    reviewCount: 189,
    deliveryTime: '30-40 phút',
    minOrder: 200000,
    tags: ['Cá hồi', 'Biệt thự Pháp', 'Âu'],
    description: 'Biệt thự Pháp cổ với khu vườn nhỏ xinh xắn và ban công ngắm phố. Chuyên các món Âu kết hợp hương vị Việt trong một không gian kín đáo, riêng tư.',
    phone: '024 5555 6666',
    address: '32C Cao Bá Quát, Quận Ba Đình, Hà Nội',
    hours: '10:00 - 22:30',
    specials: ['Giảm 10% khi đặt bàn trước'],
  },

  {
    id: 'skyline-hanoi',
    name: 'Skyline Hanoi',
    cuisine: 'View ngắm cảnh',
    image: 'https://images.unsplash.com/photo-1559314809-0d155014e29e?w=800',
    gallery: defaultGallery,
    rating: 4.7,
    reviewCount: 287,
    deliveryTime: 'Không giao',
    minOrder: 300000,
    tags: ['Rooftop', 'Cocktail', 'Hoàng hôn'],
    description: 'Ngắm toàn cảnh hồ Gươm và khu phố cổ 36 phố phường từ trên cao, thưởng thức ly cocktail trong ánh hoàng hôn rực rỡ.',
    phone: '024 7777 8888',
    address: '38 Gia Ngư, Quận Hoàn Kiếm, Hà Nội',
    hours: '15:00 - 23:00',
    specials: ['Happy hour 16:00 - 18:30: Giảm 20% nước'],
  },

  {
    id: 'banh-cuon-194',
    name: 'Bánh cuốn 194 (BD)',
    cuisine: 'Hẹn hò vỉa hè',
    image: '/images/Hẹn hò vỉa hè/Bánh cuốn 194 (BD)/IMG_6002.PNG',
    gallery: [
      '/images/Hẹn hò vỉa hè/Bánh cuốn 194 (BD)/IMG_6002.PNG',
      '/images/Hẹn hò vỉa hè/Bánh cuốn 194 (BD)/IMG_6003.PNG',
      '/images/Hẹn hò vỉa hè/Bánh cuốn 194 (BD)/IMG_6004.PNG',
    ],
    rating: 4.5,
    reviewCount: 150,
    deliveryTime: '15-20 phút',
    minOrder: 40000,
    tags: ['Bánh cuốn', 'Ăn vặt', 'Vỉa hè'],
    description: 'Bánh cuốn nóng hổi, nhân đầy đặn, nước mắm pha vừa miệng, không gian vỉa hè thoáng mát lý tưởng cho buổi hẹn hò giản dị.',
    phone: '090 123 4567',
    address: 'Hà Nội',
    hours: '06:00 - 13:00',
    specials: [],
  },
  {
    id: 'nollowa',
    name: 'Nollowa (BD)',
    cuisine: 'Hẹn hò vỉa hè',
    image: '/images/Hẹn hò vỉa hè/Nollowa (BD)/IMG_5995.PNG',
    gallery: [
      '/images/Hẹn hò vỉa hè/Nollowa (BD)/IMG_5995.PNG',
      '/images/Hẹn hò vỉa hè/Nollowa (BD)/IMG_5996.PNG',
      '/images/Hẹn hò vỉa hè/Nollowa (BD)/IMG_5997.PNG',
    ],
    rating: 4.6,
    reviewCount: 120,
    deliveryTime: '20-30 phút',
    minOrder: 45000,
    tags: ['Gà rán', 'Hàn Quốc', 'Vỉa hè'],
    description: 'Thưởng thức món gà rán Hàn Quốc giòn rụm, đậm đà trong không gian trẻ trung nhộn nhịp.',
    phone: '093 333 4444',
    address: 'Hà Nội',
    hours: '10:00 - 22:30',
    specials: [],
  },

  {
    id: 'pho-lqs',
    name: 'Phở LQS (BD)',
    cuisine: 'Hẹn hò vỉa hè',
    image: '/images/Hẹn hò vỉa hè/Phở LQS (BD)/IMG_5990.PNG',
    gallery: [
      '/images/Hẹn hò vỉa hè/Phở LQS (BD)/IMG_5990.PNG',
      '/images/Hẹn hò vỉa hè/Phở LQS (BD)/IMG_5991.PNG',
      '/images/Hẹn hò vỉa hè/Phở LQS (BD)/IMG_5992.PNG',
    ],
    rating: 4.8,
    reviewCount: 300,
    deliveryTime: '15-25 phút',
    minOrder: 50000,
    tags: ['Phở bò', 'Truyền thống', 'Ăn sáng'],
    description: 'Bát phở nóng hổi với nước dùng thanh ngọt, thịt bò mềm và bánh phở dai ngon, chuẩn hương vị truyền thống.',
    phone: '094 567 8901',
    address: 'Hà Nội',
    hours: '06:00 - 22:00',
    specials: [],
  },
  {
    id: 'aquaria-st',
    name: 'Aquaria Restaurant (ST)',
    cuisine: 'Hẹn hò sang trọng',
    image: '/images/Hẹn hò sang trọng/Aquaria Restaurant (ST)/Không gian/IMG_9313.PNG',
    gallery: [
      '/images/Hẹn hò sang trọng/Aquaria Restaurant (ST)/Không gian/IMG_9313.PNG',
      '/images/Hẹn hò sang trọng/Aquaria Restaurant (ST)/Menu/IMG_9319.PNG',
      '/images/Hẹn hò sang trọng/Aquaria Restaurant (ST)/Đồ ăn/IMG_9316.PNG',
    ],
    rating: 4.8,
    reviewCount: 215,
    deliveryTime: 'Không giao hàng',
    minOrder: 800000,
    tags: ['Sang trọng', 'Âu', 'Rooftop'],
    description: 'Không gian nhà hàng tuyệt đẹp phù hợp với những bữa tối lãng mạn sang trọng.',
    phone: '098 111 2222',
    address: 'Hà Nội',
    hours: '17:00 - 23:00',
    specials: [],
  },
  {
    id: 'fu-rong-hua',
    name: 'Fu Rong Hua Cantonese Restaurant (ST)',
    cuisine: 'Hẹn hò sang trọng',
    image: '/images/Hẹn hò sang trọng/Fu Rong Hua Cantonese Restaurant (ST)/Không gian/IMG_5716.PNG',
    gallery: [
      '/images/Hẹn hò sang trọng/Fu Rong Hua Cantonese Restaurant (ST)/Không gian/IMG_5716.PNG',
      '/images/Hẹn hò sang trọng/Fu Rong Hua Cantonese Restaurant (ST)/Menu/IMG_5711.PNG',
      '/images/Hẹn hò sang trọng/Fu Rong Hua Cantonese Restaurant (ST)/đồ ăn/IMG_5719.PNG',
    ],
    rating: 4.7,
    reviewCount: 340,
    deliveryTime: '30-40 phút',
    minOrder: 500000,
    tags: ['Dimsum', 'Trung Hoa', 'Sang trọng'],
    description: 'Nhà hàng ẩm thực Quảng Đông với các món Dimsum cao cấp và vịt quay trứ danh.',
    phone: '097 333 4444',
    address: 'Hà Nội',
    hours: '10:00 - 22:00',
    specials: [],
  },
  {
    id: 'kawasei',
    name: 'KAWASEI Japanese Restaurant(ST)',
    cuisine: 'Hẹn hò sang trọng',
    image: '/images/Hẹn hò sang trọng/KAWASEI Japanese Restaurant(ST)/không gian/IMG_5727.PNG',
    gallery: [
      '/images/Hẹn hò sang trọng/KAWASEI Japanese Restaurant(ST)/không gian/IMG_5727.PNG',
      '/images/Hẹn hò sang trọng/KAWASEI Japanese Restaurant(ST)/Menu/IMG_5722.PNG',
      '/images/Hẹn hò sang trọng/KAWASEI Japanese Restaurant(ST)/đồ ăn/IMG_5732.PNG',
    ],
    rating: 4.9,
    reviewCount: 150,
    deliveryTime: 'Không giao hàng',
    minOrder: 1500000,
    tags: ['Omakase', 'Nhật Bản', 'Cao cấp'],
    description: 'Trải nghiệm ẩm thực Omakase đẳng cấp từ bếp trưởng người Nhật.',
    phone: '096 555 6666',
    address: 'Hà Nội',
    hours: '18:00 - 23:00',
    specials: [],
  },

  {
    id: 'two-chefs',
    name: 'Two Chef’s Tonkatsu & Mau (ST)',
    cuisine: 'Hẹn hò sang trọng',
    image: '/images/Hẹn hò sang trọng/Two Chef’s Tonkatsu & Mau (ST)/Không gian/IMG_9301.PNG',
    gallery: [
      '/images/Hẹn hò sang trọng/Two Chef’s Tonkatsu & Mau (ST)/Không gian/IMG_9301.PNG',
      '/images/Hẹn hò sang trọng/Two Chef’s Tonkatsu & Mau (ST)/Menu/IMG_9298.PNG',
      '/images/Hẹn hò sang trọng/Two Chef’s Tonkatsu & Mau (ST)/Đồ ăn/IMG_9305.PNG',
    ],
    rating: 4.6,
    reviewCount: 95,
    deliveryTime: '20-30 phút',
    minOrder: 250000,
    tags: ['Tonkatsu', 'Nhật Bản', 'Ấm cúng'],
    description: 'Thịt heo chiên xù Tonkatsu giòn tan đúng điệu chuẩn Nhật Bản trong không gian sang trọng.',
    phone: '092 111 2233',
    address: 'Hà Nội',
    hours: '10:30 - 21:30',
    specials: [],
  },

];

export const vouchers: Voucher[] = [
  {
    id: 'valentine-2026',
    code: 'LOVE2026',
    title: 'Ưu đãi Valentine',
    description: 'Giảm 20% cho bữa tối lãng mạn của bạn. Có giá trị đến hết ngày 14 tháng 2 năm 2026.',
    discount: 'GIẢM 20%',
    validity: 'Đến 14 Th2',
    icon: '💝',
  },
  {
    id: 'welcome-new',
    code: 'WELCOME50K',
    title: 'Quà tặng thành viên mới',
    description: 'Ưu đãi cho lượt đặt bàn đầu tiên. Nhận ngay voucher giảm 50.000 VNĐ.',
    discount: 'GIẢM 50K',
    validity: 'Đến 28 Th2',
    icon: '🎉',
  },
  {
    id: 'lunch-combo',
    code: 'LUNCH30',
    title: 'Combo Trưa Tiết Kiệm',
    description: 'Tiết kiệm lớn khi đặt bàn dùng bữa trưa trong khung giờ từ 11:00 AM - 2:00 PM.',
    discount: 'GIẢM 30%',
    validity: 'Hàng ngày 11h-14h',
    icon: '🍽️',
  },
  {
    id: 'free-delivery',
    code: 'FREEDELIV',
    title: 'Miễn Phí Giao Hàng',
    description: 'Ưu đãi miễn phí vận chuyển cho các hóa đơn đặt món trên 200.000 VNĐ.',
    discount: 'FREE',
    validity: 'Vô thời hạn',
    icon: '🚗',
  },
];

export const timeSlots: TimeSlot[] = [
  { id: 'slot-11', time: '11:00 AM', available: true },
  { id: 'slot-12', time: '12:00 PM', available: true },
  { id: 'slot-13', time: '01:00 PM', available: false },
  { id: 'slot-14', time: '02:00 PM', available: true },
  { id: 'slot-17', time: '05:00 PM', available: true },
  { id: 'slot-18', time: '06:00 PM', available: false },
  { id: 'slot-19', time: '07:00 PM', available: true },
  { id: 'slot-20', time: '08:00 PM', available: true },
  { id: 'slot-21', time: '09:00 PM', available: true },
];