import { Restaurant, Category, Voucher, TimeSlot, HeroSlide, MenuCategory } from './types';

export const categories: Category[] = [
  { id: 'street-food', name: 'Hẹn hò "vỉa hè"', icon: '🍜' },
  { id: 'luxury', name: 'Hẹn hò sang trọng', icon: '🍷' },
  // { id: 'private', name: 'Không gian riêng tư', icon: '🕯️' },
  // { id: 'view', name: 'View ngắm cảnh', icon: '🌆' },
  // { id: 'coffee', name: 'Cà phê lãng mạn', icon: '☕' },
];

export const heroSlides: HeroSlide[] = [
  {
    id: 'hero-1',
    image: '/images/hero-1.jpg',
    title: 'Romantic Dining',
    subtitle: 'Create unforgettable memories with your loved one',
  },
  {
    id: 'hero-2',
    image: '/images/hero-2.jpg',
    title: 'Sunset Moments',
    subtitle: 'Experience love under the stars at rooftop venues',
  },
  {
    id: 'hero-3',
    image: '/images/hero-3.jpg',
    title: 'Culinary Excellence',
    subtitle: 'Taste the finest cuisines in the most intimate settings',
  },
];

export const menuCategories: MenuCategory[] = [
  {
    id: 'appetizers',
    name: 'Appetizers',
    items: [
      {
        id: 'app-1',
        name: 'Spring Rolls',
        price: 45000,
        description: 'Fresh Vietnamese spring rolls with peanut sauce',
        image: 'https://images.unsplash.com/photo-1541014741259-de529411b96a?w=400',
      },
      {
        id: 'app-2',
        name: 'Shrimp Toast',
        price: 65000,
        description: 'Crispy shrimp toast with sweet chili',
        image: 'https://images.unsplash.com/photo-1541014741259-de529411b96a?w=400',
      },
    ],
  },
  {
    id: 'mains',
    name: 'Main Courses',
    items: [
      {
        id: 'main-1',
        name: 'Premium Pho',
        price: 85000,
        description: 'Slow-cooked beef pho with fresh herbs',
        image: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=400',
      },
      {
        id: 'main-2',
        name: 'Grilled Sea Bass',
        price: 125000,
        description: 'Fresh grilled sea bass with lemongrass',
        image: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=400',
      },
    ],
  },
  {
    id: 'desserts',
    name: 'Desserts',
    items: [
      {
        id: 'dessert-1',
        name: 'Mango Sticky Rice',
        price: 35000,
        description: 'Sweet sticky rice with fresh mango',
        image: 'https://images.unsplash.com/photo-1563805042-7684c019e1cb?w=400',
      },
      {
        id: 'dessert-2',
        name: 'Chocolate Lava Cake',
        price: 45000,
        description: 'Warm chocolate cake with vanilla ice cream',
        image: 'https://images.unsplash.com/photo-1563805042-7684c019e1cb?w=400',
      },
    ],
  },
];

const defaultGallery = [
  '/images/bundau.jpg',
  '/images/menubundau.jpg',
  'https://images.unsplash.com/photo-1424847651672-bf20a4b0982b?w=600',
  'https://images.unsplash.com/photo-1559339352-11d035aa65de?w=600',
];

export const restaurants: Restaurant[] = [
  {
    id: 'bun-dau-hang-khay',
    name: 'Bún Đậu Hàng Khay',
    cuisine: 'Hẹn hò vỉa hè', // <--- Khớp với tên tab "Hẹn hò vỉa hè"
    image: '/images/bundau.jpg',
    gallery: defaultGallery,
    rating: 4.8,
    reviewCount: 342,
    deliveryTime: '15-25 mins',
    minOrder: 50000,
    tags: ['Bún đậu', 'Phố cổ', 'Dân dã'],
    description: 'Quán bún đậu mắm tôm nức tiếng khu vực phố cổ, không gian vỉa hè dân dã, nhộn nhịp, lý tưởng cho những cặp đôi thích sự giản dị và thoải mái.',
    phone: '024 1234 5678',
    address: 'Ngõ 31 Hàng Khay, Quận Hoàn Kiếm, Hà Nội',
    hours: '10:00 - 20:30',
    specials: ['Tặng kèm trà đá', 'Giảm 5% khi check-in'],
  },
  {
    id: 'french-grill',
    name: 'French Grill - JW Marriott',
    cuisine: 'Hẹn hò sang trọng', // <--- Khớp với tên tab "Hẹn hò sang trọng"
    image: 'https://images.unsplash.com/photo-1553621042-f6e147245754?w=800',
    gallery: defaultGallery,
    rating: 4.9,
    reviewCount: 256,
    deliveryTime: 'Không giao hàng',
    minOrder: 1000000,
    tags: ['Đồ Âu', 'Fine dining', 'Kỷ niệm'],
    description: 'Trải nghiệm ẩm thực Pháp đỉnh cao với không gian cực kỳ sang trọng, nến và nhạc lãng mạn dành riêng cho những dịp kỷ niệm đặc biệt.',
    phone: '024 9876 5432',
    address: 'Số 8 Đỗ Đức Dục, Nam Từ Liêm, Hà Nội',
    hours: '18:00 - 22:30',
    specials: ['Tặng bánh kem kỷ niệm', 'Rượu vang miễn phí'],
  },
  {
    id: 'salmonoid',
    name: 'Salmonoid',
    cuisine: 'Không gian riêng tư', 
    image: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=800',
    gallery: defaultGallery,
    rating: 4.6,
    reviewCount: 189,
    deliveryTime: '30-40 mins',
    minOrder: 200000,
    tags: ['Cá hồi', 'Biệt thự Pháp', 'Âu'],
    description: 'Biệt thự Pháp cổ với khu vườn nhỏ xinh xắn và ban công ngắm phố. Chuyên các món Âu kết hợp hương vị Việt trong một không gian kín đáo, riêng tư.',
    phone: '024 5555 6666',
    address: '32C Cao Bá Quát, Quận Ba Đình, Hà Nội',
    hours: '10:00 - 22:30',
    specials: ['Giảm 10% khi đặt bàn trước'],
  },
  {
    id: 'bun-cha-huong-lien',
    name: 'Bún Chả Hương Liên (Obama)',
    cuisine: 'Hẹn hò vỉa hè',
    image: 'https://images.unsplash.com/photo-1590301157890-4810ed352733?w=800',
    gallery: defaultGallery,
    rating: 4.5,
    reviewCount: 820,
    deliveryTime: '20-30 mins',
    minOrder: 80000,
    tags: ['Bún chả', 'Nổi tiếng', 'Truyền thống'],
    description: 'Thưởng thức bún chả chuẩn vị Hà Nội tại quán ăn từng đón cựu Tổng thống Mỹ Obama. Trải nghiệm ẩm thực hè phố đậm chất thủ đô.',
    phone: '024 3333 4444',
    address: '24 Lê Văn Hưu, Quận Hai Bà Trưng, Hà Nội',
    hours: '08:00 - 20:30',
    specials: ['Combo Obama giá đặc biệt'],
  },
  {
    id: 'skyline-hanoi',
    name: 'Skyline Hanoi',
    cuisine: 'View ngắm cảnh',
    image: 'https://images.unsplash.com/photo-1559314809-0d155014e29e?w=800',
    gallery: defaultGallery,
    rating: 4.7,
    reviewCount: 287,
    deliveryTime: 'Không giao',
    minOrder: 300000,
    tags: ['Rooftop', 'Cocktail', 'Hoàng hôn'],
    description: 'Ngắm toàn cảnh hồ Gươm và khu phố cổ 36 phố phường từ trên cao, thưởng thức ly cocktail trong ánh hoàng hôn rực rỡ.',
    phone: '024 7777 8888',
    address: '38 Gia Ngư, Quận Hoàn Kiếm, Hà Nội',
    hours: '15:00 - 23:00',
    specials: ['Happy hour 16:00 - 18:30: Giảm 20% menu nước'],
  },
  {
    id: 'el-gaucho-tay-ho',
    name: 'El Gaucho Argentinian Steakhouse',
    cuisine: 'Hẹn hò sang trọng',
    image: 'https://images.unsplash.com/photo-1424847651672-bf20a4b0982b?w=800',
    gallery: defaultGallery,
    rating: 4.8,
    reviewCount: 498,
    deliveryTime: '40-50 mins',
    minOrder: 500000,
    tags: ['Steak', 'Bò nhập khẩu', 'Tây Hồ'],
    description: 'Nhà hàng bít tết trứ danh với những phần thịt bò nhập khẩu hảo hạng nhất, không gian ấm cúng, sang trọng nằm ngay ven Hồ Tây lộng gió.',
    phone: '024 2222 3333',
    address: 'Số 2 Tây Hồ, Quảng An, Quận Tây Hồ, Hà Nội',
    hours: '11:00 - 23:30',
    specials: ['Tặng kèm tráng miệng cho bàn 2 người'],
  },
];

export const vouchers: Voucher[] = [
  {
    id: 'valentine-2026',
    code: 'LOVE2026',
    title: 'Valentine Special',
    description: 'Get 20% off your romantic dinner. Valid until Feb 14, 2026.',
    discount: '20% OFF',
    validity: 'Until 14 Feb',
    icon: '💝',
  },
  {
    id: 'welcome-new',
    code: 'WELCOME50K',
    title: 'Welcome Bonus',
    description: 'First order discount. Get 50,000 VND off.',
    discount: '50K OFF',
    validity: 'Until 28 Feb',
    icon: '🎉',
  },
  {
    id: 'lunch-combo',
    code: 'LUNCH30',
    title: 'Lunch Combo Deal',
    description: 'Save big on lunch orders between 11AM - 2PM.',
    discount: '30% OFF',
    validity: 'Daily 11-14h',
    icon: '🍽️',
  },
  {
    id: 'free-delivery',
    code: 'FREEDELIV',
    title: 'Free Delivery',
    description: 'Orders above 200,000 VND get free delivery.',
    discount: 'FREE',
    validity: 'Always',
    icon: '🚗',
  },
];

export const timeSlots: TimeSlot[] = [
  { id: 'slot-11', time: '11:00 AM', available: true },
  { id: 'slot-12', time: '12:00 PM', available: true },
  { id: 'slot-13', time: '1:00 PM', available: false },
  { id: 'slot-14', time: '2:00 PM', available: true },
  { id: 'slot-17', time: '5:00 PM', available: true },
  { id: 'slot-18', time: '6:00 PM', available: false },
  { id: 'slot-19', time: '7:00 PM', available: true },
  { id: 'slot-20', time: '8:00 PM', available: true },
  { id: 'slot-21', time: '9:00 PM', available: true },
];